// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDonywCIEYFywMFnFWqqx9rLmEJ_M5m7bI',
    appId: '1:371816610221:web:2559836948d6e5ecda4924',
    messagingSenderId: '371816610221',
    projectId: 'test-f4aed',
    authDomain: 'test-f4aed.firebaseapp.com',
    storageBucket: 'test-f4aed.appspot.com',
    measurementId: 'G-WL33971BF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIEYnZtQmwB4rqXcm4fcghhtfD9A4DRtE',
    appId: '1:371816610221:android:86584a971ac197feda4924',
    messagingSenderId: '371816610221',
    projectId: 'test-f4aed',
    storageBucket: 'test-f4aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBien-leifIhC9fBcP8rxS4vC_WeeR1PJI',
    appId: '1:371816610221:ios:d8fd63f4e7641d8dda4924',
    messagingSenderId: '371816610221',
    projectId: 'test-f4aed',
    storageBucket: 'test-f4aed.appspot.com',
    iosBundleId: 'com.example.testConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBien-leifIhC9fBcP8rxS4vC_WeeR1PJI',
    appId: '1:371816610221:ios:d8fd63f4e7641d8dda4924',
    messagingSenderId: '371816610221',
    projectId: 'test-f4aed',
    storageBucket: 'test-f4aed.appspot.com',
    iosBundleId: 'com.example.testConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDonywCIEYFywMFnFWqqx9rLmEJ_M5m7bI',
    appId: '1:371816610221:web:916a4fac8f0a080eda4924',
    messagingSenderId: '371816610221',
    projectId: 'test-f4aed',
    authDomain: 'test-f4aed.firebaseapp.com',
    storageBucket: 'test-f4aed.appspot.com',
    measurementId: 'G-3KSDRWJPB3',
  );
}
